### ISSUE TITLE
Замечания от 10.06.2017

### ISSUE THREAD

**Issue by QuickNickKoenig** [thanator/iLikeAnimals#1]
AnimalChoosing, ChoosingWhatToDo
- Из названия не ясно, что это фрагмент.
- Магические константы для ключей бандла.
- Форматирование.
- Закомментированный код.

AddAnimalActivity
- Название не соответствует содержимому (активити ещё и редактирует животное).
- Неиспользуемые поля.
- Магические константы для ключей интента и его значений.

**Comment by thanator** [comment]
Названия везде исправил, стринги для ключей интента больше не захардкочены, закомментированный код удалён
